name: scDock
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.4.3
  - python=3.10
  - r-fastdummies=1.7.5
  - r-igraph=2.1.4
  - r-matrix=1.7_4
  - r-curl=8.18.0
  - r-car=3.1_5
  - r-irlba=2.3.7
  - r-mass=7.3_65
  - plotly=6.5.2
  - r-patchwork=1.3.2
  - r-nmf=0.21.0
  - bioconductor-biocneighbors=2.0.0
  - r-lme4=1.1_38
  - r-ggplot2=4.0.2
  - r-data.table=1.17.8
  - bioconductor-complexheatmap=2.22.0
  - r-nloptr=2.2.1
  - bioconductor-org.hs.eg.db=3.20.0
  - bioconductor-glmgampoi=1.18.0
  - autodock-vina=1.1.2
  - hdf5=1.14.6
  - r-httr=1.4.7
  - r-sctransform=0.4.3
  - biopython==1.86
  - bioconductor-biobase=2.66.0
  - r-dplyr=1.2.0
  - r-scattermore=1.2
  - jq=1.8.1
  - r-yaml=2.3.12
  - r-hdf5r=1.3.12
  - r-matrix.utils=0.9.8
  - r-rspectra=0.16_2
  - r-cowplot=1.2.0
  - bioconductor-annotationdbi=1.68.0
  - r-rstatix=0.7.3
  - openbabel=3.1.1
  - r-ggrepel=0.9.6
  - r-devtools=2.4.6
  - r-leidenbase=0.1.32
  - r-reticulate=1.44.1
  - r-leiden=0.4.3.1
  - r-seurat=5.4.0
  - r-remotes=2.5.0
  - pubchempy=1.0.5
  - r-ggridges=0.5.7
  - rdkit==2025.9.5
  - shiny=1.12.1
  - r-pbkrtest=0.5.5
  - presto=0.7.8
  - r-miniui=0.1.2
  - zlib=1.3.1
  - requests=2.32.5
  - r-circlize=0.4.17
  - r-ggpubr=0.6.2
  - r-png=0.1_8
  - bioconductor-org.mm.eg.db=3.20.0
  - r-homologene=1.4.68.19.3.27
  - r-biocmanager=1.30.27